### ISSUE TITLE
Crash on 8 GPUs

### ISSUE THREAD

**Issue by raidersan** [mbevand/silentarmy#37] opened 2016-11-06 11:07 UTC
Had to take a GPU out of my rigs as I get an error starting the miner with 8 as I was doing with my previous zcash-miner. 7 GPU seems to be the limit

**Comment by jtremblaytdst** [comment] 2016-11-06 16:28
I get the same error dude it's the maximum client of the driver/software. Check the issue https://github.com/mbevand/silentarmy/issues/38.

Zogminer do the same things.

**Comment by mbevand** [comment] 2016-11-07 23:43
Closing as a duplicate of #38.

**Closed by mbevand** 2016-11-07 23:43 UTC
